apiVersion: v1
kind: Pod
metadata:
  name: shared-empty-dir-volume
  namespace: default
  labels:
    app: alpine
spec:
  containers:
  - name: container-1
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-ec', 'sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /mounted-data-1
  - name: container-2
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-ec', 'sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /mounted-data-2
  - name: container-3
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ['/bin/sh', '-ec', 'sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /mounted-data-3
  volumes:
    - name: data
      emptyDir: {}
  restartPolicy: Always