apiVersion: v1
kind: Pod
metadata:
  name: cm-pod-with-dir-cm
spec:
  containers:
  - name: cm-container
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "ls /etc/appconfig"]
    volumeMounts:
    - name: cm-volume
      mountPath: /etc/appconfig
  volumes:
  - name: cm-volume
    configMap:
      name: dir-map
  restartPolicy: Never
