apiVersion: v1
kind: ConfigMap
metadata:
  name: singlevalue-map
  namespace: default
data:
  partner-url: https://www.autopost.com.au

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-pod
spec:
  containers:
  - name: cm-container
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "env"]
    envFrom:
    - configMapRef:
        name: singlevalue-map

---
apiVersion: v1
kind: Pod
metadata:
  name: multi-env-pod
spec:
  containers:
  - name: multi-env-cm-container
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "sleep 10s; echo $(partner-server-location)"]
    env:
    - name: partner-server-location
      valueFrom:
        configMapKeyRef:
          name: singlevalue-map
          key: partner-url