apiVersion: v1
kind: Pod
metadata:
  name: pod-with-priv-key
spec:
  containers:
  - name: priv-key-container
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "ls etc/appconfig/; cat /etc/appconfig/private-key"]
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/appconfig
  volumes:
  - name: secret-volume
    secret:
      secretName: test-secret-key
