apiVersion: v1
kind: Pod
metadata:
  name: pod-with-generic-secret
spec:
  containers:
  - name: secret-pod
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "env"]
    envFrom:
    - secretRef:
        name: test-secret
