apiVersion: apps/v1
kind: Deployment
metadata:
  name: pageview-deployment
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  strategy: {}
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - image: ernestklu/pageviewer:v0.0.1
        name: pageviewer
        resources: {}
status: {}
