apiVersion: apps/v1
kind: Deployment
metadata:
  name:  http-pod 
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        tier: frontend 
    spec:
      containers:
      - name:  http-pod 
        image:  ernestklu/httpserver:v0.0.1
