apiVersion: v1
kind: Namespace
metadata:
  name: activity-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: activity-test
  labels:
    app: apache-server
    tier: frontend
spec:
  selector:
    matchLabels:
      app: apache-server
      tier: frontend
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache-server
        tier: frontend
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: IP_ADDR
          value: "127.0.0.1"
        - name: PORT
          value: "31000"
        ports:
        - containerPort: 80
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: activity-test
spec:
  selector:
    app: apache-server
    tier: frontend
  type: NodePort
  sessionAffinity: None
  ports:
  - name: httpd-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000